
import React from 'react';
import { AlertTriangle, Calendar, CheckCircle, Calculator, Mail, Download, ExternalLink } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';

interface QuickStatusOverviewProps {
  upcomingDeadlines: any[];
  onDeadlineClick: (deadline: any) => void;
  onShowAdvanced: () => void;
  onQuickAction: (action: string) => void;
}

const QuickStatusOverview: React.FC<QuickStatusOverviewProps> = ({
  upcomingDeadlines,
  onDeadlineClick,
  onShowAdvanced,
  onQuickAction
}) => {
  const { toast } = useToast();

  const handleGoogleCalendarExport = () => {
    if (upcomingDeadlines.length === 0) {
      toast({
        title: "No Deadlines to Export",
        description: "Please select a profile to see your tax deadlines first.",
        variant: "destructive"
      });
      return;
    }

    // Create Google Calendar URL for the next deadline
    const nextDeadline = upcomingDeadlines[0];
    const deadlineDate = new Date(nextDeadline.date);
    const startDate = new Date(deadlineDate.getTime() - 24 * 60 * 60 * 1000); // Day before
    const endDate = deadlineDate;
    
    const formatDate = (date: Date) => {
      return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
    };

    const googleCalendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(nextDeadline.title)}&dates=${formatDate(startDate)}/${formatDate(endDate)}&details=${encodeURIComponent(`UK Tax Deadline: ${nextDeadline.title}\n\nDescription: ${nextDeadline.description || 'Important tax deadline'}\n\nPriority: ${nextDeadline.priority}\n\nGenerated by PL Tax Reminder`)}&location=UK`;
    
    window.open(googleCalendarUrl, '_blank');
    toast({
      title: "Opening Google Calendar",
      description: "Adding your tax deadline to Google Calendar...",
    });
  };

  const handleActionClick = (action: string) => {
    onQuickAction(action);
    
    // Scroll to the relevant section after a short delay
    setTimeout(() => {
      const element = document.querySelector(`[value="${action}"]`) as HTMLElement;
      if (element) {
        element.click();
        element.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }, 100);
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8 animate-slide-up">
      <Card className="bg-white/95 backdrop-blur-sm border-0 shadow-lg hover-lift">
        <CardHeader className="pb-4">
          <CardTitle className="flex items-center gap-3 text-xl">
            <AlertTriangle className="h-6 w-6 text-amber-500" />
            Priority Deadlines
          </CardTitle>
        </CardHeader>
        <CardContent>
          {upcomingDeadlines.length > 0 ? (
            <div className="space-y-3">
              {upcomingDeadlines.slice(0, 2).map((deadline) => (
                <div 
                  key={deadline.id} 
                  className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-800 rounded-lg cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors" 
                  onClick={() => onDeadlineClick(deadline)}
                >
                  <div>
                    <p className="font-medium text-gray-900 dark:text-white">{deadline.title}</p>
                    <p className="text-sm text-gray-600 dark:text-gray-300">
                      {new Date(deadline.date).toLocaleDateString('en-GB', { 
                        day: 'numeric', 
                        month: 'long',
                        year: 'numeric'
                      })}
                    </p>
                  </div>
                  <Badge className={deadline.priority === 'high' ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' : 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200'}>
                    {deadline.priority}
                  </Badge>
                </div>
              ))}
              <div className="flex gap-2 mt-3">
                <Button variant="outline" className="flex-1" onClick={() => handleActionClick('deadlines')}>
                  View All Deadlines
                </Button>
                <Button 
                  variant="outline" 
                  size="sm"
                  onClick={handleGoogleCalendarExport}
                  className="flex items-center gap-2 border-blue-200 hover:bg-blue-50 dark:border-blue-700 dark:hover:bg-blue-900/20"
                  title="Add to Google Calendar"
                >
                  <ExternalLink className="h-4 w-4" />
                  <Calendar className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ) : (
            <div className="text-center py-6">
              <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-3" />
              <p className="text-gray-600 dark:text-gray-300 font-medium">All caught up!</p>
              <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">No urgent deadlines in the next 3 months</p>
              <Button variant="outline" size="sm" onClick={() => handleActionClick('calendar')}>
                View Full Calendar
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="bg-white/95 backdrop-blur-sm border-0 shadow-lg hover-lift">
        <CardHeader className="pb-4">
          <CardTitle className="flex items-center gap-3 text-xl">
            <Calendar className="h-6 w-6 text-blue-500" />
            Quick Actions
            <span className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 py-1 rounded-full ml-auto">
              Step 2
            </span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <Button 
              variant="outline" 
              className="w-full justify-start hover:bg-green-50 border-green-200 dark:border-green-700 dark:hover:bg-green-900/20" 
              onClick={() => handleActionClick('calendar')}
            >
              <Calendar className="h-4 w-4 mr-2 text-green-600" />
              View Tax Calendar
              <span className="ml-auto text-xs text-gray-500">See all dates</span>
            </Button>
            <Button 
              variant="outline" 
              className="w-full justify-start hover:bg-purple-50 border-purple-200 dark:border-purple-700 dark:hover:bg-purple-900/20" 
              onClick={() => handleActionClick('tools')}
            >
              <Calculator className="h-4 w-4 mr-2 text-purple-600" />
              Tax Tools & Calculators
              <span className="ml-auto text-xs text-gray-500">Calculate penalties</span>
            </Button>
            <Button 
              variant="outline" 
              className="w-full justify-start hover:bg-orange-50 border-orange-200 dark:border-orange-700 dark:hover:bg-orange-900/20" 
              onClick={() => handleActionClick('reminders')}
            >
              <Mail className="h-4 w-4 mr-2 text-orange-600" />
              Set Email Reminders
              <span className="ml-auto text-xs text-gray-500">Never miss a deadline</span>
            </Button>
          </div>
          
          <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-700">
            <p className="text-xs text-blue-800 dark:text-blue-200 font-medium mb-1">💡 Quick Tip</p>
            <p className="text-xs text-blue-700 dark:text-blue-300">
              Click any action above to jump directly to that section with all your personalized information.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default QuickStatusOverview;
