// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlkffiqtneywfewbtukn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sa2ZmaXF0bmV5d2Zld2J0dWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTUyNTgsImV4cCI6MjA2NTI3MTI1OH0._InY6N8ZHAEjOq39bOz-hKBaOvJ6bRJitHl6HGQuk-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);